# Generated by Django 6.0.3 on 2026-03-09 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_organization_customuser_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customUser',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='customUser',
        ),
        migrations.AddField(
            model_name='transaction',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='maker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='made_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='organization',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='main.organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='main.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
